package com.example.basic.model;
// Generated 2018-01-24 14:30:52 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Iban generated by hbm2java
 */
@Entity
@Table(name="iban"
    ,schema="public"
)
public class Iban  implements java.io.Serializable {


     private int nrDzialki;
     private Dzialki dzialki;
     private String iban;
     private Integer nrKonta;

    public Iban() {
    }

	
    public Iban(Dzialki dzialki) {
        this.dzialki = dzialki;
    }
    public Iban(Dzialki dzialki, String iban, Integer nrKonta) {
       this.dzialki = dzialki;
       this.iban = iban;
       this.nrKonta = nrKonta;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="dzialki"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="nr_dzialki", unique=true, nullable=false)
    public int getNrDzialki() {
        return this.nrDzialki;
    }
    
    public void setNrDzialki(int nrDzialki) {
        this.nrDzialki = nrDzialki;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Dzialki getDzialki() {
        return this.dzialki;
    }
    
    public void setDzialki(Dzialki dzialki) {
        this.dzialki = dzialki;
    }

    
    @Column(name="IBAN", length=100)
    public String getIban() {
        return this.iban;
    }
    
    public void setIban(String iban) {
        this.iban = iban;
    }

    
    @Column(name="nr_konta")
    public Integer getNrKonta() {
        return this.nrKonta;
    }
    
    public void setNrKonta(Integer nrKonta) {
        this.nrKonta = nrKonta;
    }




}


