package com.example.basic.model;
// Generated 2018-01-31 18:43:59 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * WyciagiJs generated by hbm2java
 */
@Entity
@Table(name="wyciagi_js"
    ,schema="public"
)
public class WyciagiJs  implements java.io.Serializable {


     private int nrWyciagu;
     private Dzialki dzialki;
     private Double kwota;
     private String data;
     private String opis;
     private Double skladka;
     private Double cynsz;
     private Integer awrbp;
     private Double wpisowe;
     private Double energiaRozpoczecieSezonu;
     private Double energiaZakonczenieSezonu;
     private Integer dyzurZRokuPopredniegoNaBiezacy;
     private Integer dyzurZRokuBiezacegoNaNastepny;
     private Double zadluzenieZRokuPoprzedniego;
     private Double licznik;

    public WyciagiJs() {
    }

	
    public WyciagiJs(int nrWyciagu, Dzialki dzialki) {
        this.nrWyciagu = nrWyciagu;
        this.dzialki = dzialki;
    }
    public WyciagiJs(int nrWyciagu, Dzialki dzialki, Double kwota, String data, String opis, Double skladka, Double cynsz, Integer awrbp, Double wpisowe, Double energiaRozpoczecieSezonu, Double energiaZakonczenieSezonu, Integer dyzurZRokuPopredniegoNaBiezacy, Integer dyzurZRokuBiezacegoNaNastepny, Double zadluzenieZRokuPoprzedniego, Double licznik) {
       this.nrWyciagu = nrWyciagu;
       this.dzialki = dzialki;
       this.kwota = kwota;
       this.data = data;
       this.opis = opis;
       this.skladka = skladka;
       this.cynsz = cynsz;
       this.awrbp = awrbp;
       this.wpisowe = wpisowe;
       this.energiaRozpoczecieSezonu = energiaRozpoczecieSezonu;
       this.energiaZakonczenieSezonu = energiaZakonczenieSezonu;
       this.dyzurZRokuPopredniegoNaBiezacy = dyzurZRokuPopredniegoNaBiezacy;
       this.dyzurZRokuBiezacegoNaNastepny = dyzurZRokuBiezacegoNaNastepny;
       this.zadluzenieZRokuPoprzedniego = zadluzenieZRokuPoprzedniego;
       this.licznik = licznik;
    }
   
     @Id 

    
    @Column(name="nr_wyciagu", unique=true, nullable=false)
    public int getNrWyciagu() {
        return this.nrWyciagu;
    }
    
    public void setNrWyciagu(int nrWyciagu) {
        this.nrWyciagu = nrWyciagu;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="nr_dzialki", nullable=false)
    public Dzialki getDzialki() {
        return this.dzialki;
    }
    
    public void setDzialki(Dzialki dzialki) {
        this.dzialki = dzialki;
    }

    
    @Column(name="kwota", precision=17, scale=17)
    public Double getKwota() {
        return this.kwota;
    }
    
    public void setKwota(Double kwota) {
        this.kwota = kwota;
    }

    
    @Column(name="data")
    public String getData() {
        return this.data;
    }
    
    public void setData(String data) {
        this.data = data;
    }

    
    @Column(name="opis")
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }

    
    @Column(name="skladka", precision=17, scale=17)
    public Double getSkladka() {
        return this.skladka;
    }
    
    public void setSkladka(Double skladka) {
        this.skladka = skladka;
    }

    
    @Column(name="cynsz", precision=17, scale=17)
    public Double getCynsz() {
        return this.cynsz;
    }
    
    public void setCynsz(Double cynsz) {
        this.cynsz = cynsz;
    }

    
    @Column(name="AWRBP")
    public Integer getAwrbp() {
        return this.awrbp;
    }
    
    public void setAwrbp(Integer awrbp) {
        this.awrbp = awrbp;
    }

    
    @Column(name="wpisowe", precision=17, scale=17)
    public Double getWpisowe() {
        return this.wpisowe;
    }
    
    public void setWpisowe(Double wpisowe) {
        this.wpisowe = wpisowe;
    }

    
    @Column(name="energia_rozpoczecie_sezonu", precision=17, scale=17)
    public Double getEnergiaRozpoczecieSezonu() {
        return this.energiaRozpoczecieSezonu;
    }
    
    public void setEnergiaRozpoczecieSezonu(Double energiaRozpoczecieSezonu) {
        this.energiaRozpoczecieSezonu = energiaRozpoczecieSezonu;
    }

    
    @Column(name="energia_zakonczenie_sezonu", precision=17, scale=17)
    public Double getEnergiaZakonczenieSezonu() {
        return this.energiaZakonczenieSezonu;
    }
    
    public void setEnergiaZakonczenieSezonu(Double energiaZakonczenieSezonu) {
        this.energiaZakonczenieSezonu = energiaZakonczenieSezonu;
    }

    
    @Column(name="dyzur z roku popredniego na biezacy")
    public Integer getDyzurZRokuPopredniegoNaBiezacy() {
        return this.dyzurZRokuPopredniegoNaBiezacy;
    }
    
    public void setDyzurZRokuPopredniegoNaBiezacy(Integer dyzurZRokuPopredniegoNaBiezacy) {
        this.dyzurZRokuPopredniegoNaBiezacy = dyzurZRokuPopredniegoNaBiezacy;
    }

    
    @Column(name="dyzur z roku biezacego na nastepny")
    public Integer getDyzurZRokuBiezacegoNaNastepny() {
        return this.dyzurZRokuBiezacegoNaNastepny;
    }
    
    public void setDyzurZRokuBiezacegoNaNastepny(Integer dyzurZRokuBiezacegoNaNastepny) {
        this.dyzurZRokuBiezacegoNaNastepny = dyzurZRokuBiezacegoNaNastepny;
    }

    
    @Column(name="zadluzenie z roku poprzedniego", precision=17, scale=17)
    public Double getZadluzenieZRokuPoprzedniego() {
        return this.zadluzenieZRokuPoprzedniego;
    }
    
    public void setZadluzenieZRokuPoprzedniego(Double zadluzenieZRokuPoprzedniego) {
        this.zadluzenieZRokuPoprzedniego = zadluzenieZRokuPoprzedniego;
    }

    
    @Column(name="licznik", precision=17, scale=17)
    public Double getLicznik() {
        return this.licznik;
    }
    
    public void setLicznik(Double licznik) {
        this.licznik = licznik;
    }




}


