package com.example.basic.model;
// Generated 2018-01-31 18:43:59 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Zobowiazania generated by hbm2java
 */
@Entity
@Table(name="zobowiazania"
    ,schema="public"
)
public class Zobowiazania  implements java.io.Serializable {


     private int nrZobowiazania;
     private Dzialki dzialki;
     private int rokRozliczeniowy;
     private Double bilansOtwarcia;
     private Double skladka;
     private Double czynsz;
     private Double anr;
     private Double wpiowe;
     private Double energiaRozpocecieSezonu;
     private Double energiaAkonczeniaSeoznu;
     private Double dyzurZPoprzedniegoNaBiezacy;
     private Double dyzurZRokuBiezacegoNaNastepny;
     private Double zadluzenieZRokuPoprzedniego;
     private Double zobowiazaniaRazemZBo;

    public Zobowiazania() {
    }

	
    public Zobowiazania(int nrZobowiazania, Dzialki dzialki, int rokRozliczeniowy) {
        this.nrZobowiazania = nrZobowiazania;
        this.dzialki = dzialki;
        this.rokRozliczeniowy = rokRozliczeniowy;
    }
    public Zobowiazania(int nrZobowiazania, Dzialki dzialki, int rokRozliczeniowy, Double bilansOtwarcia, Double skladka, Double czynsz, Double anr, Double wpiowe, Double energiaRozpocecieSezonu, Double energiaAkonczeniaSeoznu, Double dyzurZPoprzedniegoNaBiezacy, Double dyzurZRokuBiezacegoNaNastepny, Double zadluzenieZRokuPoprzedniego, Double zobowiazaniaRazemZBo) {
       this.nrZobowiazania = nrZobowiazania;
       this.dzialki = dzialki;
       this.rokRozliczeniowy = rokRozliczeniowy;
       this.bilansOtwarcia = bilansOtwarcia;
       this.skladka = skladka;
       this.czynsz = czynsz;
       this.anr = anr;
       this.wpiowe = wpiowe;
       this.energiaRozpocecieSezonu = energiaRozpocecieSezonu;
       this.energiaAkonczeniaSeoznu = energiaAkonczeniaSeoznu;
       this.dyzurZPoprzedniegoNaBiezacy = dyzurZPoprzedniegoNaBiezacy;
       this.dyzurZRokuBiezacegoNaNastepny = dyzurZRokuBiezacegoNaNastepny;
       this.zadluzenieZRokuPoprzedniego = zadluzenieZRokuPoprzedniego;
       this.zobowiazaniaRazemZBo = zobowiazaniaRazemZBo;
    }
   
     @Id 

    
    @Column(name="nr_zobowiazania", unique=true, nullable=false)
    public int getNrZobowiazania() {
        return this.nrZobowiazania;
    }
    
    public void setNrZobowiazania(int nrZobowiazania) {
        this.nrZobowiazania = nrZobowiazania;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="nr_dzialki", nullable=false)
    public Dzialki getDzialki() {
        return this.dzialki;
    }
    
    public void setDzialki(Dzialki dzialki) {
        this.dzialki = dzialki;
    }

    
    @Column(name="rok rozliczeniowy", nullable=false)
    public int getRokRozliczeniowy() {
        return this.rokRozliczeniowy;
    }
    
    public void setRokRozliczeniowy(int rokRozliczeniowy) {
        this.rokRozliczeniowy = rokRozliczeniowy;
    }

    
    @Column(name="bilans otwarcia", precision=17, scale=17)
    public Double getBilansOtwarcia() {
        return this.bilansOtwarcia;
    }
    
    public void setBilansOtwarcia(Double bilansOtwarcia) {
        this.bilansOtwarcia = bilansOtwarcia;
    }

    
    @Column(name="skladka", precision=17, scale=17)
    public Double getSkladka() {
        return this.skladka;
    }
    
    public void setSkladka(Double skladka) {
        this.skladka = skladka;
    }

    
    @Column(name="czynsz", precision=17, scale=17)
    public Double getCzynsz() {
        return this.czynsz;
    }
    
    public void setCzynsz(Double czynsz) {
        this.czynsz = czynsz;
    }

    
    @Column(name="ANR", precision=17, scale=17)
    public Double getAnr() {
        return this.anr;
    }
    
    public void setAnr(Double anr) {
        this.anr = anr;
    }

    
    @Column(name="wpiowe", precision=17, scale=17)
    public Double getWpiowe() {
        return this.wpiowe;
    }
    
    public void setWpiowe(Double wpiowe) {
        this.wpiowe = wpiowe;
    }

    
    @Column(name="energia_rozpocecie_sezonu", precision=17, scale=17)
    public Double getEnergiaRozpocecieSezonu() {
        return this.energiaRozpocecieSezonu;
    }
    
    public void setEnergiaRozpocecieSezonu(Double energiaRozpocecieSezonu) {
        this.energiaRozpocecieSezonu = energiaRozpocecieSezonu;
    }

    
    @Column(name="energia_akonczenia_seoznu", precision=17, scale=17)
    public Double getEnergiaAkonczeniaSeoznu() {
        return this.energiaAkonczeniaSeoznu;
    }
    
    public void setEnergiaAkonczeniaSeoznu(Double energiaAkonczeniaSeoznu) {
        this.energiaAkonczeniaSeoznu = energiaAkonczeniaSeoznu;
    }

    
    @Column(name="dyzur z poprzedniego na biezacy", precision=17, scale=17)
    public Double getDyzurZPoprzedniegoNaBiezacy() {
        return this.dyzurZPoprzedniegoNaBiezacy;
    }
    
    public void setDyzurZPoprzedniegoNaBiezacy(Double dyzurZPoprzedniegoNaBiezacy) {
        this.dyzurZPoprzedniegoNaBiezacy = dyzurZPoprzedniegoNaBiezacy;
    }

    
    @Column(name="dyzur z roku biezacego na nastepny", precision=17, scale=17)
    public Double getDyzurZRokuBiezacegoNaNastepny() {
        return this.dyzurZRokuBiezacegoNaNastepny;
    }
    
    public void setDyzurZRokuBiezacegoNaNastepny(Double dyzurZRokuBiezacegoNaNastepny) {
        this.dyzurZRokuBiezacegoNaNastepny = dyzurZRokuBiezacegoNaNastepny;
    }

    
    @Column(name="zadluzenie z roku poprzedniego", precision=17, scale=17)
    public Double getZadluzenieZRokuPoprzedniego() {
        return this.zadluzenieZRokuPoprzedniego;
    }
    
    public void setZadluzenieZRokuPoprzedniego(Double zadluzenieZRokuPoprzedniego) {
        this.zadluzenieZRokuPoprzedniego = zadluzenieZRokuPoprzedniego;
    }

    
    @Column(name="zobowiazania razem z BO", precision=17, scale=17)
    public Double getZobowiazaniaRazemZBo() {
        return this.zobowiazaniaRazemZBo;
    }
    
    public void setZobowiazaniaRazemZBo(Double zobowiazaniaRazemZBo) {
        this.zobowiazaniaRazemZBo = zobowiazaniaRazemZBo;
    }




}


